version: "3"
services:
  subconverter:
    image: "mercuryzz/subconverter:0.8.2"
    container_name: subconverter
    restart: always
    ports: 
      - "25500:25500"

  subweb:
    image: "mercuryzz/subweb:latest"
    container_name: subweb
    restart: always
    ports:
      - "58080:80"